apiVersion: v1
kind: Namespace
metadata:
  name: production
  labels:
    env: production
    managed-by: argocd
---
apiVersion: v1
kind: Namespace
metadata:
  name: staging
  labels:
    env: staging
    managed-by: argocd
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    env: platform
    managed-by: argocd
---
apiVersion: v1
kind: Namespace
metadata:
  name: argo-rollouts
  labels:
    env: platform
    managed-by: argocd
